/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.AccountController;
import core.controllers.TransactionController;
import core.controllers.UserController;
import core.controllers.utils.Response;
import core.models.Account;
import core.models.Transaction;
import core.models.User;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BankAppView extends javax.swing.JFrame {

        // private ArrayList<Account> accounts;
        // private ArrayList<Transaction> transactions;
        // private ArrayList<User> users;

        /**
         * Creates new form BankFrame
         */
        public BankAppView() {
                initComponents();
                // this.accounts = new ArrayList<>();
                // this.transactions = new ArrayList<>();
                // this.users = new ArrayList<>();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                IDTextfield = new javax.swing.JTextField();
                firstNameTextField = new javax.swing.JTextField();
                lastNameTextField = new javax.swing.JTextField();
                ageTextField = new javax.swing.JTextField();
                registerButton = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                userIDTextField = new javax.swing.JTextField();
                initialBalanceTextField = new javax.swing.JTextField();
                createButton = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                sourceAccountTextField = new javax.swing.JTextField();
                destinAccountTextField = new javax.swing.JTextField();
                amountTextField = new javax.swing.JTextField();
                typeTransactionComboBox = new javax.swing.JComboBox<>();
                execTransactionButton = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                listUsersTable = new javax.swing.JTable();
                refreshUsersButton = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                listAccountsTable = new javax.swing.JTable();
                refeshAccountsButton = new javax.swing.JButton();
                jPanel6 = new javax.swing.JPanel();
                jLabel16 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                listTransactionsTable = new javax.swing.JTable();
                refreshTransactionsButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("Register User");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel2.setText("ID");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Firstname");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel4.setText("Lastname");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("Age");

                registerButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                registerButton.setText("Register");
                registerButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                registerButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(239, 239, 239)
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(0, 270, Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(jLabel2))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(IDTextfield,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lastNameTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(ageTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(firstNameTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                .addContainerGap())
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(259, 259, 259)
                                                                .addComponent(registerButton)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(IDTextfield,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(firstNameTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lastNameTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(ageTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(registerButton)
                                                                .addContainerGap(83, Short.MAX_VALUE)));

                jTabbedPane1.addTab("Register User", jPanel1);

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel6.setText("Create Account");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("User ID");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel8.setText("Initial Balance");

                createButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                createButton.setText("Create");
                createButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(238, 238, 238)
                                                                                                .addComponent(jLabel6))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(jLabel8))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(initialBalanceTextField)
                                                                                                                .addComponent(userIDTextField,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                521,
                                                                                                                                Short.MAX_VALUE))))
                                                                .addContainerGap())
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(265, 265, 265)
                                                                .addComponent(createButton)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel6)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(userIDTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel7))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(initialBalanceTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel8))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(createButton)
                                                                .addContainerGap(163, Short.MAX_VALUE)));

                jTabbedPane1.addTab("Create Account", jPanel2);

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel9.setText("Make Transaction");

                jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel10.setText("Type");

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel11.setText("Source Account");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel12.setText("Destination Account");

                jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel13.setText("Amount");

                destinAccountTextField.setToolTipText("");

                typeTransactionComboBox
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Deposit", "Withdraw", "Transfer" }));

                execTransactionButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                execTransactionButton.setText("Execute");
                execTransactionButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                execTransactionButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel10)
                                                                                                                .addComponent(jLabel13)
                                                                                                                .addComponent(jLabel12)
                                                                                                                .addComponent(jLabel11))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(destinAccountTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(sourceAccountTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(typeTransactionComboBox,
                                                                                                                                0,
                                                                                                                                485,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(amountTextField,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(227, 227, 227)
                                                                                                .addComponent(jLabel9)))
                                                                .addContainerGap())
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(255, 255, 255)
                                                                .addComponent(execTransactionButton)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(typeTransactionComboBox,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel10))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(sourceAccountTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel11))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(destinAccountTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel12))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(amountTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel13))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(execTransactionButton)
                                                                .addContainerGap(83, Short.MAX_VALUE)));

                jTabbedPane1.addTab("Make Transaction", jPanel3);

                jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel14.setText("List Users");

                listUsersTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "ID", "Fullname", "Age", "Number of Accounts"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Long.class, java.lang.String.class, java.lang.Integer.class,
                                        java.lang.Integer.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane2.setViewportView(listUsersTable);

                refreshUsersButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                refreshUsersButton.setText("Refresh");
                refreshUsersButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                refreshUsersButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jScrollPane2,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                616,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addContainerGap())
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(62, 62, 62)
                                                                                                .addComponent(jLabel14)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(refreshUsersButton)
                                                                                                .addGap(88, 88, 88)))));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(refreshUsersButton))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                264, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("List Users", jPanel4);

                jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel15.setText("List Accounts");

                listAccountsTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null },
                                                { null, null, null }
                                },
                                new String[] {
                                                "ID", "User ID", "Balance"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.Long.class, java.lang.Double.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane3.setViewportView(listAccountsTable);

                refeshAccountsButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                refeshAccountsButton.setText("Refresh");
                refeshAccountsButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                refeshAccountsButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                616, Short.MAX_VALUE)
                                                                .addContainerGap())
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(refeshAccountsButton)
                                                                .addGap(90, 90, 90)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel15)
                                                                                .addComponent(refeshAccountsButton))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                264, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("List Accounts", jPanel5);

                jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel16.setText("List Transactions");

                listTransactionsTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Type", "Source Account ID", "Destination Account ID", "Amount"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.Double.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(listTransactionsTable);

                refreshTransactionsButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
                refreshTransactionsButton.setText("Refresh");
                refreshTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                refreshTransactionsButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                616, Short.MAX_VALUE)
                                                                .addContainerGap())
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(64, 64, 64)
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(refreshTransactionsButton)
                                                                .addGap(89, 89, 89)));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(refreshTransactionsButton))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                264, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("List Transactions", jPanel6);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registerButtonActionPerformed
                // Se obtiene los datos de cada campo de texto
                String id = IDTextfield.getText();
                String firstname = firstNameTextField.getText();
                String lastname = lastNameTextField.getText();
                String age = ageTextField.getText();

                // Llamamos al controlador para crear un usuario y esperamos su respuesta
                Response response = UserController.registerUser(id, firstname, lastname, age);

                // Dependiendo del codigo de respuesta mostrar mensajes de dialogo
                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message",
                                        JOptionPane.INFORMATION_MESSAGE);

                        // Si todo marchó bien se registra el usuario y se limpian los campos de text
                        IDTextfield.setText("");
                        firstNameTextField.setText("");
                        lastNameTextField.setText("");
                        ageTextField.setText("");
                        ageTextField.setText("");
                }
        }// GEN-LAST:event_registerButtonActionPerformed

        private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createButtonActionPerformed
                // Obtenemos los campos necesarios
                String userId = userIDTextField.getText();
                String initialBalance = initialBalanceTextField.getText();

                // Se llama al controlador para agregar una cuenta
                Response response = AccountController.createAccount(userId, initialBalance);

                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message",
                                        JOptionPane.INFORMATION_MESSAGE);

                        userIDTextField.setText("");
                        initialBalanceTextField.setText("");
                }

        }// GEN-LAST:event_createButtonActionPerformed

        private void execTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_execTransactionButtonActionPerformed
                // Obtenemos los datos del formulario
                String type = typeTransactionComboBox.getItemAt(typeTransactionComboBox.getSelectedIndex());
                String sourceAccountId = sourceAccountTextField.getText();
                String destinationAccountId = destinAccountTextField.getText();
                String amount = amountTextField.getText();

                // LLamamos al controlador para hacer una transaccion. El controller valida que
                // tipo de transaccion es
                Response response = TransactionController.makeTransaction(type, destinationAccountId, sourceAccountId,
                                amount);

                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message",
                                        JOptionPane.INFORMATION_MESSAGE);

                        sourceAccountTextField.setText("");
                        destinAccountTextField.setText("");
                        amountTextField.setText("");
                }

        }// GEN-LAST:event_execTransactionButtonActionPerformed

        private void refreshUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshUsersButtonActionPerformed
                // Crear una tabla
                DefaultTableModel model = (DefaultTableModel) listUsersTable.getModel();
                model.setRowCount(0);

                // Llama al controller para capturar los usuarios registrados. El controller los
                // ordena
                Response response = UserController.getUsers();

                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {

                        // Convertir el objeto devuelto a una lista de usuarios
                        @SuppressWarnings("unchecked")
                        List<User> users = (List<User>) response.getObject();
                        // System.out.println(users);

                        // this.users=response.getObject();
                        // this.users.sort((obj1, obj2) -> (obj1.getId() - obj2.getId()));

                        // Mostrarr la tabla
                        for (User user : users) {
                                model.addRow(new Object[] { user.getId(),
                                                user.getFirstname() + " " + user.getLastname(), user.getAge(),
                                                user.getNumAccounts() });
                        }
                }
        }// GEN-LAST:event_refreshUsersButtonActionPerformed

        private void refeshAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refeshAccountsButtonActionPerformed
                // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) listAccountsTable.getModel();
                model.setRowCount(0);

                Response response = AccountController.getAccounts();

                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {

                        // Convertir el objeto devuelto a una lista de cuentas
                        @SuppressWarnings("unchecked")
                        List<Account> accounts = (List<Account>) response.getObject();
                        for (Account account : accounts) {
                                model.addRow(new Object[] { account.getId(), account.getOwner().getId(),
                                                account.getBalance() });
                        }
                }
        }// GEN-LAST:event_refeshAccountsButtonActionPerformed

        private void refreshTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshTransactionsButtonActionPerformed
                // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) listTransactionsTable.getModel();
                model.setRowCount(0);

                Response response = TransactionController.getTransactions();

                if (response.getStatus() >= 500) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.ERROR_MESSAGE);
                } else if (response.getStatus() >= 400) {
                        JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(),
                                        JOptionPane.WARNING_MESSAGE);
                } else {

                        // Convertir el objeto devuelto a una lista de transacciones
                        @SuppressWarnings("unchecked")
                        List<Transaction> transactions = (List<Transaction>) response.getObject();
                        for (Transaction transaction : transactions) {
                                model.addRow(new Object[] { transaction.getType().name(),
                                                (transaction.getSourceAccount() != null
                                                                ? transaction.getSourceAccount().getId()
                                                                : "None"),
                                                (transaction.getDestinationAccount() != null
                                                                ? transaction.getDestinationAccount().getId()
                                                                : "None"),
                                                transaction.getAmount() });
                        }
                }

                // ArrayList<Transaction> transactionsCopy = (ArrayList<Transaction>)
                // this.transactions.clone();
                // Collections.reverse(transactionsCopy);

                // for (Transaction transaction : transactionsCopy) {
                // model.addRow(new Object[] { transaction.getType().name(),
                // (transaction.getSourceAccount() != null ?
                // transaction.getSourceAccount().getId() : "None"),
                // (transaction.getDestinationAccount() != null ?
                // transaction.getDestinationAccount().getId()
                // : "None"),
                // transaction.getAmount() });
                // }
        }// GEN-LAST:event_refreshTransactionsButtonActionPerformed

        /**
         * @param args the command line arguments
         */
        // public static void main(String args[]) {
        // /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
        // default look and feel.
        // * For details see
        // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        // */
        // try {
        // for (javax.swing.UIManager.LookAndFeelInfo info :
        // javax.swing.UIManager.getInstalledLookAndFeels()) {
        // if ("Nimbus".equals(info.getName())) {
        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
        // break;
        // }
        // }
        // } catch (ClassNotFoundException ex) {
        // java.util.logging.Logger.getLogger(BankAppView.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (InstantiationException ex) {
        // java.util.logging.Logger.getLogger(BankAppView.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (IllegalAccessException ex) {
        // java.util.logging.Logger.getLogger(BankAppView.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        // java.util.logging.Logger.getLogger(BankAppView.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // }
        // //</editor-fold>
        //
        // /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        // public void run() {
        // new BankAppView().setVisible(true);
        // }
        // });
        // }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField IDTextfield;
        private javax.swing.JTextField ageTextField;
        private javax.swing.JTextField amountTextField;
        private javax.swing.JButton createButton;
        private javax.swing.JTextField destinAccountTextField;
        private javax.swing.JButton execTransactionButton;
        private javax.swing.JTextField firstNameTextField;
        private javax.swing.JTextField initialBalanceTextField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextField lastNameTextField;
        private javax.swing.JTable listAccountsTable;
        private javax.swing.JTable listTransactionsTable;
        private javax.swing.JTable listUsersTable;
        private javax.swing.JButton refeshAccountsButton;
        private javax.swing.JButton refreshTransactionsButton;
        private javax.swing.JButton refreshUsersButton;
        private javax.swing.JButton registerButton;
        private javax.swing.JTextField sourceAccountTextField;
        private javax.swing.JComboBox<String> typeTransactionComboBox;
        private javax.swing.JTextField userIDTextField;
        // End of variables declaration//GEN-END:variables
}
